project:
  type: website

website:
  title: ""
  lang: pt
  #body-footer: "subscribe.html"
  description: "FintechScientist por Marcus Silva"
  reader-mode: true
  favicon: "images/blog-logo-icon.png"
  navbar:
    logo: "images/blog-logo.png"
    left:
      - text: ""
    right:
      - text: Blog
        href: blog.qmd
      - text: Slides
        href: slides.qmd
      - text: Sobre
        href: index.qmd
      #- text: Webinars
      #  href: webinars.qmd
      # - text: Cursos
      #  href: courses.qmd
        #href: credit_risk_landing_page.qmd
      - icon: linkedin
        href: https://linkedin.com/in/marcuos/
      - icon: twitter
        href: https://twitter.com/fintscientist
  cookie-consent:
    type: express
    style: headline
  open-graph: true
  google-analytics:
    tracking-id: "G-VBYL9R2RYQ"
    anonymize-ip: true

format:
  html:
    theme: litera
    css: styles.css
    linkcolor: "#6A38D4"



