project:
  type: website

website:
  title: ""
  lang: pt
  body-footer: "subscribe.html"
  description: "FintechScientist por Marcus Silva"
  reader-mode: true
  navbar:
    logo: "images/blog-logo.png"
    favicon: "images/blog-logo-icon.png"
    right:
      - text: Blog
        href: blog.qmd
      - text: Slides
        href: slides.qmd
      - text: Sobre
        href: about.qmd
      - text: Webinars
        href: webinars.qmd
      - icon: linkedin
        href: linkedin.com/in/marcuos/
      - icon: twitter
        href: twitter.com/
  cookie-consent:
    type: express
    style: headline
  open-graph: true
  google-analytics:
    tracking-id: "UA-344887522"
    anonymize-ip: true

format:
  html:
    theme: litera
    css: styles.css
    linkcolor: "#6A38D4"



